Repository MIT-Emerging-Talent/ET6-foundations-group-22, pull requests merged in 2025-01, with the labels that each got.

#39 Calculate Minutes Wasted (Adding the fun doc and unittest)
  solutions/convert_hours_to_minutes.py
  solutions/tests/test_convert_hours_to_minutes.py
Labels: Challenge

#51 Added the largest number files
  solutions/largest_number.py
  solutions/tests/test_largest_number.py
Labels: Challenge

#42 Check_Number_Type
  solutions/check_number_type.py
  solutions/tests/test_check_number_type.py
Labels: Challenge

#52 add Group Retrospective
  collaboration/retrospective.md
Labels: documentation

#34 Add dictionary merge solution and related test
  .vscode/settings.json
  solutions/README.md
  solutions/__init__.py
  solutions/merge_dictionaries.py
  solutions/tests/README.md
  solutions/tests/test_merge_dictionaries.py
Labels: Challenge

#48 Swap_letters review
  solutions/Swap_letters.py
  solutions/tests/test_Swap_letters.py
Labels: Challenge

#32 Capital letters
  .pylintrc
  solutions/convert_to_capital.py
  solutions/convert_to_uppercase.py
  solutions/tests/test_convert_to_capital.py
  solutions/tests/test_convert_to_uppercase.py
Labels: Challenge

#44 Anagram finder
  .vscode/settings.json
  solutions/README.md
  solutions/Remove_Duplicates.py
  solutions/Swap_letters.py
  solutions/Time_Conversion.py
  solutions/anagram_finder.py
  solutions/calculate_square_area.py
  solutions/check_number_type.py
  solutions/convert_hours_to_minutes.py
  solutions/convert_to_capital.py
  solutions/convert_to_uppercase.py
  solutions/is_palindrome.py
  solutions/largest_number.py
  solutions/merge_dictionaries.py
  solutions/sum_of_list.py
  solutions/tests/README.md
  solutions/tests/test_Remove_Duplicate.py
  solutions/tests/test_Swap_letters.py
  solutions/tests/test_Time_Conversion.py
  solutions/tests/test_anagram_finder.py
  solutions/tests/test_calculate_square_area.py
  solutions/tests/test_check_number_type.py
  solutions/tests/test_convert_hours_to_minutes.py
  solutions/tests/test_convert_to_capital.py
  solutions/tests/test_convert_to_uppercase.py
  solutions/tests/test_is_palindrome.py
  solutions/tests/test_largest_number.py
  solutions/tests/test_merge_dictionaries.py
  solutions/tests/test_sum_of_list.py
  solutions/tests/test_word_frequency.py
  solutions/word_frequency.py
Labels: Challenge

#57 adding header to check_number_type
  solutions/anagram_finder.py
  solutions/check_number_type.py
  solutions/tests/test_anagram_finder.py
  solutions/tests/test_check_number_type.py
Labels: enhancement
